"""init tables

Revision ID: 1a23cd81082c
Revises: 
Create Date: 2025-06-26 22:43:02.117969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1a23cd81082c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_platform_casbin_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_platform_casbin_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sa.Enum('Policy', 'Grouping', name='ptypeenum'), nullable=True),
    sa.Column('v0', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('v1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('v2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v3', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v4', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ptype', 'user_platform_casbin_rule', ['ptype'], unique=False)
    op.create_index('idx_v0', 'user_platform_casbin_rule', ['v0'], unique=False)
    op.create_index('idx_v1_v2', 'user_platform_casbin_rule', ['v1', 'v2'], unique=False)
    op.create_table('user_platform_casbin_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_platform_oauth_provider',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('provider_type', sa.Enum('Oauth', 'Saml', 'Oidc', name='providetypeenum'), nullable=False),
    sa.Column('grant_type', sa.Enum('AUTHORIZATION_CODE', 'IMPLICIT', 'PASSWORD', 'CLIENT_CREDENTIALS', 'REFRESH_TOKEN', name='granttype'), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('client_secret', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('authorization_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('userinfo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('additional_auth_params', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_status', sa.Boolean(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', 'client_id', 'client_secret', name='uq_provider_name_client_credentials')
    )
    op.create_table('user_platform_oauth_state',
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('redirect_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('user_platform_revoked_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_platform_revoked_token_token'), 'user_platform_revoked_token', ['token'], unique=True)
    op.create_table('user_platform_security_policy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password_min_length', sa.Integer(), nullable=False),
    sa.Column('allow_common_password', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_platform_transform_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('error_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_platform_user',
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('user_platform_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_resource_id', sa.Integer(), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('operation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_platform_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_platform_field_mapping',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('source_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transform_rule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['user_platform_oauth_provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_platform_mfa_secuity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_platform_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_platform_oauth_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_uid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_token', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('access_token', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('refresh_token', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['user_platform_oauth_provider.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_platform_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_id', 'provider_uid', name='uq_user_account')
    )
    op.create_table('user_platform_sso_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('refresh_token', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('device_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_platform_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index('ix_sso_refresh_token', 'user_platform_sso_session', ['refresh_token'], unique=True)
    op.create_index('ix_sso_session_token', 'user_platform_sso_session', ['session_token'], unique=True)
    op.create_index('ix_sso_user_expires', 'user_platform_sso_session', ['user_id', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sso_user_expires', table_name='user_platform_sso_session')
    op.drop_index('ix_sso_session_token', table_name='user_platform_sso_session')
    op.drop_index('ix_sso_refresh_token', table_name='user_platform_sso_session')
    op.drop_table('user_platform_sso_session')
    op.drop_table('user_platform_oauth_account')
    op.drop_table('user_platform_mfa_secuity')
    op.drop_table('user_platform_field_mapping')
    op.drop_table('user_platform_audit_log')
    op.drop_table('user_platform_user')
    op.drop_table('user_platform_transform_log')
    op.drop_table('user_platform_security_policy')
    op.drop_index(op.f('ix_user_platform_revoked_token_token'), table_name='user_platform_revoked_token')
    op.drop_table('user_platform_revoked_token')
    op.drop_table('user_platform_oauth_state')
    op.drop_table('user_platform_oauth_provider')
    op.drop_table('user_platform_casbin_system')
    op.drop_index('idx_v1_v2', table_name='user_platform_casbin_rule')
    op.drop_index('idx_v0', table_name='user_platform_casbin_rule')
    op.drop_index('idx_ptype', table_name='user_platform_casbin_rule')
    op.drop_table('user_platform_casbin_rule')
    op.drop_table('user_platform_casbin_role')
    # ### end Alembic commands ###
